package modelo;
// Generated 19-may-2025 18:33:36 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Concesionario generated by hbm2java
 */
public class Concesionario  implements java.io.Serializable {


     private Integer idConcesionario;
     private String nombre;
     private String direccion;
     private String telefono;
     private String correo;
     private Set inventarios = new HashSet(0);
     private Set empleados = new HashSet(0);

    public Concesionario() {
    }

	
    public Concesionario(String nombre, String direccion, String telefono, String correo) {
        this.nombre = nombre;
        this.direccion = direccion;
        this.telefono = telefono;
        this.correo = correo;
    }
    public Concesionario(String nombre, String direccion, String telefono, String correo, Set inventarios, Set empleados) {
       this.nombre = nombre;
       this.direccion = direccion;
       this.telefono = telefono;
       this.correo = correo;
       this.inventarios = inventarios;
       this.empleados = empleados;
    }
   
    public Integer getIdConcesionario() {
        return this.idConcesionario;
    }
    
    public void setIdConcesionario(Integer idConcesionario) {
        this.idConcesionario = idConcesionario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Set getInventarios() {
        return this.inventarios;
    }
    
    public void setInventarios(Set inventarios) {
        this.inventarios = inventarios;
    }
    public Set getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set empleados) {
        this.empleados = empleados;
    }




}


