package modelo;
// Generated 19-may-2025 18:33:36 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private String dni;
     private Concesionario concesionario;
     private String nombre;
     private String apellidos;
     private String email;
     private String telefono;
     private String direccion;
     private String puesto;
     private String contrasenya;
     private Set inventarios = new HashSet(0);

    public Empleado() {
    }

	
    public Empleado(String dni, Concesionario concesionario, String nombre, String apellidos, String email, String telefono, String direccion, String puesto, String contrasenya) {
        this.dni = dni;
        this.concesionario = concesionario;
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.email = email;
        this.telefono = telefono;
        this.direccion = direccion;
        this.puesto = puesto;
        this.contrasenya = contrasenya;
    }
    public Empleado(String dni, Concesionario concesionario, String nombre, String apellidos, String email, String telefono, String direccion, String puesto, String contrasenya, Set inventarios) {
       this.dni = dni;
       this.concesionario = concesionario;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.email = email;
       this.telefono = telefono;
       this.direccion = direccion;
       this.puesto = puesto;
       this.contrasenya = contrasenya;
       this.inventarios = inventarios;
    }
   
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public Concesionario getConcesionario() {
        return this.concesionario;
    }
    
    public void setConcesionario(Concesionario concesionario) {
        this.concesionario = concesionario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getPuesto() {
        return this.puesto;
    }
    
    public void setPuesto(String puesto) {
        this.puesto = puesto;
    }
    public String getContrasenya() {
        return this.contrasenya;
    }
    
    public void setContrasenya(String contrasenya) {
        this.contrasenya = contrasenya;
    }
    public Set getInventarios() {
        return this.inventarios;
    }
    
    public void setInventarios(Set inventarios) {
        this.inventarios = inventarios;
    }




}


