package modelo;
// Generated 19-may-2025 18:33:36 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pago generated by hbm2java
 */
public class Pago  implements java.io.Serializable {


     private Integer idPago;
     private Reserva reserva;
     private Date fechaPago;
     private BigDecimal precioTotal;
     private String metodoPago;
     private String estadoPago;
     private Set transaccions = new HashSet(0);

    public Pago() {
    }

	
    public Pago(Reserva reserva, Date fechaPago, BigDecimal precioTotal, String metodoPago, String estadoPago) {
        this.reserva = reserva;
        this.fechaPago = fechaPago;
        this.precioTotal = precioTotal;
        this.metodoPago = metodoPago;
        this.estadoPago = estadoPago;
    }
    public Pago(Reserva reserva, Date fechaPago, BigDecimal precioTotal, String metodoPago, String estadoPago, Set transaccions) {
       this.reserva = reserva;
       this.fechaPago = fechaPago;
       this.precioTotal = precioTotal;
       this.metodoPago = metodoPago;
       this.estadoPago = estadoPago;
       this.transaccions = transaccions;
    }

    public Pago(Integer idPago, Reserva reserva, Date fechaPago, BigDecimal precioTotal, String metodoPago, String estadoPago) {
        this.idPago=idPago;
        this.reserva=reserva;
        this.fechaPago=fechaPago;
        this.precioTotal=precioTotal;
        this.metodoPago=metodoPago;
        this.estadoPago=estadoPago;
    }
    
   
    public Integer getIdPago() {
        return this.idPago;
    }
    
    public void setIdPago(Integer idPago) {
        this.idPago = idPago;
    }
    public Reserva getReserva() {
        return this.reserva;
    }
    
    public void setReserva(Reserva reserva) {
        this.reserva = reserva;
    }
    public Date getFechaPago() {
        return this.fechaPago;
    }
    
    public void setFechaPago(Date fechaPago) {
        this.fechaPago = fechaPago;
    }
    public BigDecimal getPrecioTotal() {
        return this.precioTotal;
    }
    
    public void setPrecioTotal(BigDecimal precioTotal) {
        this.precioTotal = precioTotal;
    }
    public String getMetodoPago() {
        return this.metodoPago;
    }
    
    public void setMetodoPago(String metodoPago) {
        this.metodoPago = metodoPago;
    }
    public String getEstadoPago() {
        return this.estadoPago;
    }
    
    public void setEstadoPago(String estadoPago) {
        this.estadoPago = estadoPago;
    }
    public Set getTransaccions() {
        return this.transaccions;
    }
    
    public void setTransaccions(Set transaccions) {
        this.transaccions = transaccions;
    }




}


