package modelo;
// Generated 18-may-2025 22:13:47 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Reserva generated by hbm2java
 */
public class Reserva  implements java.io.Serializable {


     private Integer idReserva;
     private Cliente cliente;
     private Vehiculo vehiculo;
     private String estado;
     private Date fechaCreacion;
     private Date fechaRecogida;
     private Set pagos = new HashSet(0);

    public Reserva() {
    }

	
    public Reserva(Cliente cliente, Vehiculo vehiculo, String estado, Date fechaCreacion) {
        this.cliente = cliente;
        this.vehiculo = vehiculo;
        this.estado = estado;
        this.fechaCreacion = fechaCreacion;
    }
    public Reserva(Cliente cliente, Vehiculo vehiculo, String estado, Date fechaCreacion, Date fechaRecogida, Set pagos) {
       this.cliente = cliente;
       this.vehiculo = vehiculo;
       this.estado = estado;
       this.fechaCreacion = fechaCreacion;
       this.fechaRecogida = fechaRecogida;
       this.pagos = pagos;
    }
   
    public Integer getIdReserva() {
        return this.idReserva;
    }
    
    public void setIdReserva(Integer idReserva) {
        this.idReserva = idReserva;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Vehiculo getVehiculo() {
        return this.vehiculo;
    }
    
    public void setVehiculo(Vehiculo vehiculo) {
        this.vehiculo = vehiculo;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaRecogida() {
        return this.fechaRecogida;
    }
    
    public void setFechaRecogida(Date fechaRecogida) {
        this.fechaRecogida = fechaRecogida;
    }
    public Set getPagos() {
        return this.pagos;
    }
    
    public void setPagos(Set pagos) {
        this.pagos = pagos;
    }




}


