package modelo;
// Generated 18-may-2025 22:13:47 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Transaccion generated by hbm2java
 */
public class Transaccion  implements java.io.Serializable {


     private Integer idTransaccion;
     private Date fechaTransaccion;
     private BigDecimal precio;
     private String metodoPago;
     private String estado;
     private Set pagos = new HashSet(0);

    public Transaccion() {
    }

	
    public Transaccion(Date fechaTransaccion, BigDecimal precio, String metodoPago, String estado) {
        this.fechaTransaccion = fechaTransaccion;
        this.precio = precio;
        this.metodoPago = metodoPago;
        this.estado = estado;
    }
    public Transaccion(Date fechaTransaccion, BigDecimal precio, String metodoPago, String estado, Set pagos) {
       this.fechaTransaccion = fechaTransaccion;
       this.precio = precio;
       this.metodoPago = metodoPago;
       this.estado = estado;
       this.pagos = pagos;
    }
   
    public Integer getIdTransaccion() {
        return this.idTransaccion;
    }
    
    public void setIdTransaccion(Integer idTransaccion) {
        this.idTransaccion = idTransaccion;
    }
    public Date getFechaTransaccion() {
        return this.fechaTransaccion;
    }
    
    public void setFechaTransaccion(Date fechaTransaccion) {
        this.fechaTransaccion = fechaTransaccion;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public String getMetodoPago() {
        return this.metodoPago;
    }
    
    public void setMetodoPago(String metodoPago) {
        this.metodoPago = metodoPago;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getPagos() {
        return this.pagos;
    }
    
    public void setPagos(Set pagos) {
        this.pagos = pagos;
    }




}


