package modelo;
// Generated 18-may-2025 22:13:47 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Vehiculo generated by hbm2java
 */
public class Vehiculo  implements java.io.Serializable {


     private String matricula;
     private Inventario inventario;
     private String marca;
     private String modelo;
     private int anio;
     private BigDecimal precio;
     private String estado;
     private boolean disponibilidad;
     private Set reservas = new HashSet(0);

    public Vehiculo() {
    }

	
    public Vehiculo(String matricula, Inventario inventario, String marca, String modelo, int anio, BigDecimal precio, String estado, boolean disponibilidad) {
        this.matricula = matricula;
        this.inventario = inventario;
        this.marca = marca;
        this.modelo = modelo;
        this.anio = anio;
        this.precio = precio;
        this.estado = estado;
        this.disponibilidad = disponibilidad;
    }
    public Vehiculo(String matricula, Inventario inventario, String marca, String modelo, int anio, BigDecimal precio, String estado, boolean disponibilidad, Set reservas) {
       this.matricula = matricula;
       this.inventario = inventario;
       this.marca = marca;
       this.modelo = modelo;
       this.anio = anio;
       this.precio = precio;
       this.estado = estado;
       this.disponibilidad = disponibilidad;
       this.reservas = reservas;
    }
   
    public String getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }
    public Inventario getInventario() {
        return this.inventario;
    }
    
    public void setInventario(Inventario inventario) {
        this.inventario = inventario;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public int getAnio() {
        return this.anio;
    }
    
    public void setAnio(int anio) {
        this.anio = anio;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public boolean isDisponibilidad() {
        return this.disponibilidad;
    }
    
    public void setDisponibilidad(boolean disponibilidad) {
        this.disponibilidad = disponibilidad;
    }
    public Set getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set reservas) {
        this.reservas = reservas;
    }




}


