package modelo;
// Generated 19-may-2025 18:33:36 by Hibernate Tools 4.3.1

import java.beans.Transient;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Inventario generated by hbm2java
 */
public class Inventario implements java.io.Serializable {

    private Integer idInventario;
    private Concesionario concesionario;
    private Empleado empleado;
    private int totalVehiculos;
    private Date ultimaActualizacion;
    private Set vehiculos = new HashSet(0);

    public Inventario() {
    }

    public Inventario(Concesionario concesionario, Empleado empleado, int totalVehiculos, Date ultimaActualizacion) {
        this.concesionario = concesionario;
        this.empleado = empleado;
        this.totalVehiculos = totalVehiculos;
        this.ultimaActualizacion = ultimaActualizacion;
    }

    public Inventario(Concesionario concesionario, Empleado empleado, int totalVehiculos, Date ultimaActualizacion, Set vehiculos) {
        this.concesionario = concesionario;
        this.empleado = empleado;
        this.totalVehiculos = totalVehiculos;
        this.ultimaActualizacion = ultimaActualizacion;
        this.vehiculos = vehiculos;
    }

    public Integer getIdInventario() {
        return this.idInventario;
    }

    public void setIdInventario(Integer idInventario) {
        this.idInventario = idInventario;
    }

    public Concesionario getConcesionario() {
        return this.concesionario;
    }

    public void setConcesionario(Concesionario concesionario) {
        this.concesionario = concesionario;
    }

    public Empleado getEmpleado() {
        return this.empleado;
    }

    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }

    @Transient          // ← le indica a Hibernate que NO hay columna asociada
    public int getTotalVehiculos() {
        return vehiculos == null ? 0 : vehiculos.size();
    }

    public void setTotalVehiculos(int totalVehiculos) {
        this.totalVehiculos = totalVehiculos;
    }

    public Date getUltimaActualizacion() {
        return this.ultimaActualizacion;
    }

    public void setUltimaActualizacion(Date ultimaActualizacion) {
        this.ultimaActualizacion = ultimaActualizacion;
    }

    public Set getVehiculos() {
        return this.vehiculos;
    }

    public void setVehiculos(Set vehiculos) {
        this.vehiculos = vehiculos;
    }

}
